version: 1.0.{build}
 
install:
  - cmd: cd build
  - ps: wget https://github.com/premake/premake-core/releases/download/v5.0.0.alpha4/premake-5.0.0.alpha4-windows.zip -OutFile premake5.zip
  - cmd: dir
  - cmd: 7z x premake5.zip
  - cmd: premake5 --version
  - cmd: del premake5.zip
  
build_script:
  - cmd: cd build
  - cmd: premake5 gmake
  - cmd: make clean
  - cmd: make
