language: c
matrix:
  fast_finish: true
  include:
    # OS X Mavericks
    - os: osx
      env: C_COMPILER=clang TOOLSET=clang LTO=on ARCH=native

    - os: osx
      env: C_COMPILER=gcc TOOLSET=gcc LTO=on ARCH=native

    # Container-based Ubuntu 12.04 LTS Server Edition 64 bit (doesn't support 32-bit includes)
    - os: linux
      sudo: false
      env: C_COMPILER=gcc TOOLSET=gcc LTO=on ARCH=native

    - os: linux
      sudo: false
      env: C_COMPILER=clang TOOLSET=clang LTO=off ARCH=native

    # Ubuntu 14.04 LTS Server Edition 64 bit
    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-aarch64-linux-gnu
            - g++-aarch64-linux-gnu
      env: C_COMPILER=aarch64-linux-gnu-gcc QEMU_INTERPRETER=qemu-aarch64-static TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
      env: C_COMPILER=arm-linux-gnueabi-gcc QEMU_INTERPRETER=qemu-arm-static TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: C_COMPILER=powerpc-linux-gnu-gcc QEMU_INTERPRETER=qemu-ppc64-static TOOLSET=gcc LTO=on ARCH=x64

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: C_COMPILER=powerpc-linux-gnu-gcc QEMU_INTERPRETER=qemu-ppc-static TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
      env: C_COMPILER=gcc-4.8 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - gcc-4.8-multilib
      env: C_COMPILER=gcc-4.8 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env: C_COMPILER=gcc-4.9 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gcc-4.9-multilib
      env: C_COMPILER=gcc-4.9 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: C_COMPILER=gcc-5 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-5-multilib
      env: C_COMPILER=gcc-5 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: C_COMPILER=gcc-6 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gcc-6-multilib
      env: C_COMPILER=gcc-6 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env: C_COMPILER=gcc-7 TOOLSET=gcc LTO=on

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gcc-7-multilib
      env: C_COMPILER=gcc-7 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env: C_COMPILER=clang-3.5 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env: C_COMPILER=clang-3.6 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: C_COMPILER=clang-3.8 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env: C_COMPILER=clang-3.9 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: C_COMPILER=clang-4.0 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: C_COMPILER=clang-5.0 TOOLSET=clang LTO=off ARCH=native

before_install:
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-macosx.tar.gz -O premake.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz -O premake.tar.gz; fi

script:
  - tar zxvf premake.tar.gz
  - ./premake5 gmake --toolset=$TOOLSET --lto=$LTO --arch=$ARCH
  - $C_COMPILER -v
  - make CC=$C_COMPILER
  - ls -la ./bin/Release/
  - file ./bin/Release/*
